import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./layout.css";
import {Providers} from "./providers";
import Header from "@/components/layout/Header";
import Content from "@/components/layout/Content";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body className={inter.className}>
        <Providers>
          <div>
            <Header></Header>
            <Content>{children}</Content>
            <Footer></Footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
